In [2]:
from fmp_fetch.online_dataset import Dataset

In [4]:
d = Dataset(['DECK', 'IBKR', 'LULU'], metrics={'close_price': 'price', 'pe': '', 'price_to_fcf': 'pfcf'}, start_date='2025-06-01', end_date='2025-06-06').data

2025-06-06 11:22:29 - online_dataset.py:234 - INFO - Fetching price data for 3 symbols from 2025-06-01 to 2025-06-06
100%|██████████| 3/3 [00:01<00:00,  1.73it/s]
2025-06-06 11:22:31 - online_dataset.py:182 - INFO - Fetching income_statement for 3 symbols
100%|██████████| 3/3 [00:02<00:00,  1.47it/s]
2025-06-06 11:22:33 - online_dataset.py:182 - INFO - Fetching cashflow_statement for 3 symbols
100%|██████████| 3/3 [00:02<00:00,  1.41it/s]
2025-06-06 11:22:35 - online_dataset.py:289 - INFO - Computing PE ratios
100%|██████████| 3/3 [00:00<00:00, 338.92it/s]
2025-06-06 11:22:35 - online_dataset.py:344 - INFO - Computing price to FCF ratios
100%|██████████| 3/3 [00:00<00:00, 206.14it/s]

In [5]:
d

                   close_price         pe price_to_fcf
symbol date
DECK   2025-06-01          NaN        NaT          NaT
       2025-06-02       105.01  16.594582    16.728589
       2025-06-03       105.83  16.724166    16.859219
       2025-06-04       105.81  16.721005    16.856033
       2025-06-05       108.32  17.117657    17.255888
       2025-06-06       109.35  17.280426    17.419971
IBKR   2025-06-01          NaN        NaT          NaT
       2025-06-02       208.20  28.844952     2.636778
       2025-06-03       207.91  28.804775     2.633105
       2025-06-04       206.03  28.544311     2.609296
       2025-06-05       206.82  28.653761     2.619301
       2025-06-06       213.08  29.521049     2.698581
LULU   2025-06-01          NaN        NaT          NaT
       2025-06-02       322.95  21.693841    24.860412
       2025-06-03       334.91  22.497242    25.781083
       2025-06-04       335.19   22.51605    25.802637
       2025-06-05       330.78  22.219813    25.463159
       2025-06-06       266.52  17.903212    20.516479